---
parameters:
  - name: TF_Environment
    type: string
    displayName: 'Type of TF_Environment'
    values:
      - dev
      - it
      - uat
      - prod
    default: dev
  - name: TF_Version
    type: string
    displayName: 'Type of TF_Version'
    values:
      - 1.3.0
      - 1.5.5
      - 1.7.5
      - 1.8.3
    default: 1.8.3
  - name: PLAN_STAGE
    type: boolean
    displayName: 'Execute terraform plan'
    default: true

trigger:
  - none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 
    displayName: 'Terraform plan'
    jobs:
      - job: plan
        displayName: 'Initialize and Plan the terraform'
        steps:
          - template: templates/tf_plan.yml
