---
parameters:
  - name: TF_Environment
    displayName: 'Type of TF_Environment'
    type: string
    values:
      - dev
      - it
      - uat
      - prod
    default: dev
  - name: TF_Version
    displayName: 'Type of TF_Version'
    type: string
    values:
      - 1.3.0
      - 1.5.5
      - 1.7.5
    default: 1.7.5 
  - name: PLAN_STAGE
    displayName: 'Execute terraform plan'
    type: boolean
    default: rue    

trigger:
  - none
